# Generated by Django 3.1.6 on 2021-02-13 20:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='Undefined-book-name', max_length=254)),
                ('author_name', models.CharField(default='Undefined-author-name', max_length=254)),
                ('author_lastname', models.CharField(default='Undefined-author-lastname', max_length=254)),
                ('link', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=254), size=None)),
                ('label', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=254)),
                ('user_settings', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('access_type', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], max_length=8)),
                ('drive', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivelogin.users')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('text_pointer', models.IntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivelogin.books')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivelogin.users')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivelogin.users'),
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_pointer', models.IntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivelogin.books')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivelogin.users')),
            ],
        ),
    ]
